/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: JonnyMANSON (https://sketchfab.com/JonnyMANSON)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-mixamo-retextured-model-62990b050faf48dd8590d5d15872857c
Title: Free Mixamo retextured Model
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import astronautScene from '../assets/3d/astronaut.glb'

const Astronaut = ({ currentAnimation, ...props }) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(astronautScene)
  const { actions } = useAnimations(animations, group)

  // Log available animations for debugging
  useEffect(() => {
    if (actions) {
      console.log('Available Astronaut animations:', Object.keys(actions));
    }
  }, [actions]);

  // Play animation based on currentAnimation prop
  useEffect(() => {
    if (actions) {
      Object.values(actions).forEach((action) => action?.stop());
      
      if (currentAnimation && actions[currentAnimation]) {
        actions[currentAnimation].reset().fadeIn(0.5).play();
      } else if (Object.keys(actions).length > 0) {
        // If specified animation doesn't exist, play the first available animation
        const firstAnimation = Object.keys(actions)[0];
        console.log('Playing first available animation:', firstAnimation);
        actions[firstAnimation].reset().fadeIn(0.5).play();
      }
    }
  }, [actions, currentAnimation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={1.315}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="RootNode0_96" scale={0.01}>
                <group name="skeletal3_95">
                  <group name="GLTF_created_0">
                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                    <skinnedMesh
                      name="Object_8"
                      geometry={nodes.Object_8.geometry}
                      material={materials['Material_0.001']}
                      skeleton={nodes.Object_8.skeleton}
                    />
                    <skinnedMesh
                      name="Object_10"
                      geometry={nodes.Object_10.geometry}
                      material={materials['Material_1.001']}
                      skeleton={nodes.Object_10.skeleton}
                    />
                    <skinnedMesh
                      name="Object_12"
                      geometry={nodes.Object_12.geometry}
                      material={materials['Material_2.001']}
                      skeleton={nodes.Object_12.skeleton}
                    />
                    <group name="Mesh_0001_92" />
                    <group name="Mesh_1001_93" />
                    <group name="Mesh_2001_94" />
                  </group>
                </group>
              </group>
              <group name="RootNode001_189" scale={0.01}>
                <group name="skeletal001_188">
                  <group name="GLTF_created_1">
                    <primitive object={nodes.GLTF_created_1_rootJoint} />
                    <skinnedMesh
                      name="Object_108"
                      geometry={nodes.Object_108.geometry}
                      material={materials['Material_0.002']}
                      skeleton={nodes.Object_108.skeleton}
                    />
                    <group name="Mesh_0002_187" />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Astronaut;
