/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: JonnyMANSON (https://sketchfab.com/JonnyMANSON)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-mixamo-retextured-model-62990b050faf48dd8590d5d15872857c
Title: Free Mixamo retextured Model
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import roboScene from '../assets/3d/robo.glb'

const Robo = ({ currentAnimation, ...props }) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(roboScene)
  const { actions } = useAnimations(animations, group)

  // Log available animations for debugging
  useEffect(() => {
    if (actions) {
      console.log('Available Robo animations:', Object.keys(actions));
    }
  }, [actions]);

  // Play animation based on currentAnimation prop
  useEffect(() => {
    if (actions) {
      Object.values(actions).forEach((action) => action?.stop());
      
      if (currentAnimation && actions[currentAnimation]) {
        actions[currentAnimation].reset().fadeIn(0.5).play();
      } else if (Object.keys(actions).length > 0) {
        // If specified animation doesn't exist, play the first available animation
        const firstAnimation = Object.keys(actions)[0];
        console.log('Playing first available animation:', firstAnimation);
        actions[firstAnimation].reset().fadeIn(0.5).play();
      }
    }
  }, [actions, currentAnimation]);

  return (
    // <group ref={group} {...props} dispose={null}>
    //   <group name="Sketchfab_Scene">
    //     <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={1.659}>
    //       <group
    //         name="9b2b62bf994549fc8b81f17f620a4dedfbx"
    //         rotation={[Math.PI / 2, 0, 0]}
    //         scale={0.01}>
    //         <group name="Object_2">
    //           <group name="RootNode">
    //             <group name="Object_4">
    //               <primitive object={nodes._rootJoint} />
    //               <skinnedMesh
    //                 name="Object_7"
    //                 geometry={nodes.Object_7.geometry}
    //                 material={materials['Material.002']}
    //                 skeleton={nodes.Object_7.skeleton}
    //               />
    //               <skinnedMesh
    //                 name="Object_8"
    //                 geometry={nodes.Object_8.geometry}
    //                 material={materials.Ch44_body1}
    //                 skeleton={nodes.Object_8.skeleton}
    //               />
    //               <skinnedMesh
    //                 name="Object_9"
    //                 geometry={nodes.Object_9.geometry}
    //                 material={materials.Ch44_Body}
    //                 skeleton={nodes.Object_9.skeleton}
    //               />
    //               <skinnedMesh
    //                 name="Object_11"
    //                 geometry={nodes.Object_11.geometry}
    //                 material={materials.Ch44_Body}
    //                 skeleton={nodes.Object_11.skeleton}
    //               />
    //               <skinnedMesh
    //                 name="Object_13"
    //                 geometry={nodes.Object_13.geometry}
    //                 material={materials.Ch44_Body}
    //                 skeleton={nodes.Object_13.skeleton}
    //               />
    //               <skinnedMesh
    //                 name="Object_15"
    //                 geometry={nodes.Object_15.geometry}
    //                 material={materials['Material.005']}
    //                 skeleton={nodes.Object_15.skeleton}
    //               />
    //               <skinnedMesh
    //                 name="Object_17"
    //                 geometry={nodes.Object_17.geometry}
    //                 material={materials['Material.001']}
    //                 skeleton={nodes.Object_17.skeleton}
    //               />
    //               <skinnedMesh
    //                 name="Object_19"
    //                 geometry={nodes.Object_19.geometry}
    //                 material={materials.Ch44_body1}
    //                 skeleton={nodes.Object_19.skeleton}
    //               />
    //               <skinnedMesh
    //                 name="Object_21"
    //                 geometry={nodes.Object_21.geometry}
    //                 material={materials['Material.003']}
    //                 skeleton={nodes.Object_21.skeleton}
    //               />
    //               <skinnedMesh
    //                 name="Object_23"
    //                 geometry={nodes.Object_23.geometry}
    //                 material={materials['Material.003']}
    //                 skeleton={nodes.Object_23.skeleton}
    //               />
    //               <skinnedMesh
    //                 name="Object_25"
    //                 geometry={nodes.Object_25.geometry}
    //                 material={materials.Ch44_Body}
    //                 skeleton={nodes.Object_25.skeleton}
    //               />
    //               <skinnedMesh
    //                 name="Object_27"
    //                 geometry={nodes.Object_27.geometry}
    //                 material={materials.Ch44_Body}
    //                 skeleton={nodes.Object_27.skeleton}
    //               />
    //               <skinnedMesh
    //                 name="Object_29"
    //                 geometry={nodes.Object_29.geometry}
    //                 material={materials.Ch44_Body}
    //                 skeleton={nodes.Object_29.skeleton}
    //               />
    //               <skinnedMesh
    //                 name="Object_31"
    //                 geometry={nodes.Object_31.geometry}
    //                 material={materials['Material.003']}
    //                 skeleton={nodes.Object_31.skeleton}
    //               />
    //               <skinnedMesh
    //                 name="Object_33"
    //                 geometry={nodes.Object_33.geometry}
    //                 material={materials['Material.003']}
    //                 skeleton={nodes.Object_33.skeleton}
    //               />
    //               <skinnedMesh
    //                 name="Object_35"
    //                 geometry={nodes.Object_35.geometry}
    //                 material={materials['Material.003']}
    //                 skeleton={nodes.Object_35.skeleton}
    //               />
    //               <skinnedMesh
    //                 name="Object_37"
    //                 geometry={nodes.Object_37.geometry}
    //                 material={materials['Material.001']}
    //                 skeleton={nodes.Object_37.skeleton}
    //               />
    //               <skinnedMesh
    //                 name="Object_39"
    //                 geometry={nodes.Object_39.geometry}
    //                 material={materials['Material.003']}
    //                 skeleton={nodes.Object_39.skeleton}
    //               />
    //               <skinnedMesh
    //                 name="Object_41"
    //                 geometry={nodes.Object_41.geometry}
    //                 material={materials['Material.001']}
    //                 skeleton={nodes.Object_41.skeleton}
    //               />
    //               <skinnedMesh
    //                 name="Object_43"
    //                 geometry={nodes.Object_43.geometry}
    //                 material={materials['Material.004']}
    //                 skeleton={nodes.Object_43.skeleton}
    //               />
    //               <skinnedMesh
    //                 name="Object_45"
    //                 geometry={nodes.Object_45.geometry}
    //                 material={materials['Material.003']}
    //                 skeleton={nodes.Object_45.skeleton}
    //               />
    //               <skinnedMesh
    //                 name="Object_47"
    //                 geometry={nodes.Object_47.geometry}
    //                 material={materials['Material.003']}
    //                 skeleton={nodes.Object_47.skeleton}
    //               />
    //               <skinnedMesh
    //                 name="Object_49"
    //                 geometry={nodes.Object_49.geometry}
    //                 material={materials['Material.001']}
    //                 skeleton={nodes.Object_49.skeleton}
    //               />
    //               <skinnedMesh
    //                 name="Object_51"
    //                 geometry={nodes.Object_51.geometry}
    //                 material={materials['Material.003']}
    //                 skeleton={nodes.Object_51.skeleton}
    //               />
    //               <skinnedMesh
    //                 name="Object_53"
    //                 geometry={nodes.Object_53.geometry}
    //                 material={materials['Material.003']}
    //                 skeleton={nodes.Object_53.skeleton}
    //               />
    //               <skinnedMesh
    //                 name="Object_55"
    //                 geometry={nodes.Object_55.geometry}
    //                 material={materials['Material.001']}
    //                 skeleton={nodes.Object_55.skeleton}
    //               />
    //               <skinnedMesh
    //                 name="Object_57"
    //                 geometry={nodes.Object_57.geometry}
    //                 material={materials.Ch44_body1}
    //                 skeleton={nodes.Object_57.skeleton}
    //               />
    //               <group name="Object_6" position={[0, 141.635, 15.009]} />
    //               <group
    //                 name="Object_10"
    //                 position={[-0.726, 161.462, 4.869]}
    //                 rotation={[-1.62, 0.004, -0.087]}
    //                 scale={16.019}
    //               />
    //               <group
    //                 name="Object_12"
    //                 position={[-0.726, 161.462, 4.869]}
    //                 rotation={[-1.62, 0.004, -0.087]}
    //                 scale={16.019}
    //               />
    //               <group
    //                 name="Object_14"
    //                 position={[-0.726, 161.462, 4.869]}
    //                 rotation={[-1.62, 0.004, -0.087]}
    //                 scale={16.019}
    //               />
    //               <group
    //                 name="Object_16"
    //                 position={[-0.726, 161.462, 4.869]}
    //                 rotation={[-1.62, 0.004, -0.087]}
    //                 scale={16.019}
    //               />
    //               <group
    //                 name="Object_18"
    //                 position={[-0.726, 161.462, 4.869]}
    //                 rotation={[-1.62, 0.004, -0.087]}
    //                 scale={16.019}
    //               />
    //               <group
    //                 name="Object_20"
    //                 position={[-0.726, 161.462, 4.869]}
    //                 rotation={[-1.688, 0.01, -0.086]}
    //                 scale={16.019}
    //               />
    //               <group
    //                 name="Object_22"
    //                 position={[-0.726, 161.462, 4.869]}
    //                 rotation={[-1.62, 0.004, -0.087]}
    //                 scale={16.019}
    //               />
    //               <group
    //                 name="Object_24"
    //                 position={[-0.726, 161.462, 4.869]}
    //                 rotation={[-1.62, 0.004, -0.087]}
    //                 scale={16.019}
    //               />
    //               <group
    //                 name="Object_26"
    //                 position={[-0.726, 161.462, 4.869]}
    //                 rotation={[-1.62, 0.004, -0.087]}
    //                 scale={16.019}
    //               />
    //               <group
    //                 name="Object_28"
    //                 position={[-0.726, 161.462, 4.869]}
    //                 rotation={[-1.622, -0.118, -0.171]}
    //                 scale={18.451}
    //               />
    //               <group
    //                 name="Object_30"
    //                 position={[-0.726, 161.462, 4.869]}
    //                 rotation={[-1.62, 0.004, -0.087]}
    //                 scale={16.019}
    //               />
    //               <group
    //                 name="Object_32"
    //                 position={[-0.726, 161.462, 4.869]}
    //                 rotation={[-1.62, 0.004, -0.087]}
    //                 scale={16.019}
    //               />
    //               <group
    //                 name="Object_34"
    //                 position={[-0.726, 161.462, 4.869]}
    //                 rotation={[-1.62, 0.004, -0.087]}
    //                 scale={16.019}
    //               />
    //               <group
    //                 name="Object_36"
    //                 position={[-0.726, 161.462, 4.869]}
    //                 rotation={[-1.62, 0.004, -0.087]}
    //                 scale={16.019}
    //               />
    //               <group
    //                 name="Object_38"
    //                 position={[-0.726, 161.462, 4.869]}
    //                 rotation={[-1.62, 0.004, -0.087]}
    //                 scale={16.533}
    //               />
    //               <group
    //                 name="Object_40"
    //                 position={[-0.726, 161.462, 4.869]}
    //                 rotation={[-1.62, 0.004, -0.087]}
    //                 scale={15.551}
    //               />
    //               <group
    //                 name="Object_42"
    //                 position={[-0.726, 161.462, 4.869]}
    //                 rotation={[-1.62, 0.004, -0.087]}
    //                 scale={15.203}
    //               />
    //               <group
    //                 name="Object_44"
    //                 position={[-0.726, 161.462, 4.869]}
    //                 rotation={[-1.62, 0.004, -0.087]}
    //                 scale={16.019}
    //               />
    //               <group
    //                 name="Object_46"
    //                 position={[-0.726, 161.462, 4.869]}
    //                 rotation={[-1.62, 0.004, -0.087]}
    //                 scale={16.019}
    //               />
    //               <group
    //                 name="Object_48"
    //                 position={[-0.726, 161.462, 4.869]}
    //                 rotation={[-1.62, 0.004, -0.087]}
    //                 scale={16.019}
    //               />
    //               <group
    //                 name="Object_50"
    //                 position={[-0.726, 161.462, 4.869]}
    //                 rotation={[-1.62, 0.004, -0.087]}
    //                 scale={16.019}
    //               />
    //               <group
    //                 name="Object_52"
    //                 position={[-0.726, 161.462, 4.869]}
    //                 rotation={[-1.62, 0.004, -0.087]}
    //                 scale={16.019}
    //               />
    //               <group
    //                 name="Object_54"
    //                 position={[-0.429, 183.247, 3.91]}
    //                 rotation={[-1.337, -0.237, -0.025]}
    //                 scale={1.436}
    //               />
    //               <group
    //                 name="Object_56"
    //                 position={[-0.726, 161.462, 4.869]}
    //                 rotation={[-1.62, 0.004, -0.087]}
    //                 scale={16.019}
    //               />
    //               <group
    //                 name="Light"
    //                 position={[407.625, 590.386, -100.545]}
    //                 rotation={[1.89, 0.881, -2.045]}
    //                 scale={100}>
    //                 <group name="Object_116" rotation={[Math.PI / 2, 0, 0]}>
    //                   <group name="Object_117" />
    //                 </group>
    //               </group>
    //               <group
    //                 name="Camera"
    //                 position={[735.889, 495.831, 692.579]}
    //                 rotation={[-Math.PI, 0.756, 2.68]}
    //                 scale={100}>
    //                 <group name="Object_119" />
    //               </group>
    //               <group
    //                 name="Light001"
    //                 position={[407.625, 590.386, -100.545]}
    //                 rotation={[1.89, 0.881, -2.045]}
    //                 scale={100}>
    //                 <group name="Object_121" rotation={[Math.PI / 2, 0, 0]}>
    //                   <group name="Object_122" />
    //                 </group>
    //               </group>
    //               <group
    //                 name="Camera001"
    //                 position={[735.889, 495.831, 692.579]}
    //                 rotation={[-Math.PI, 0.756, 2.68]}
    //                 scale={100}>
    //                 <group name="Object_124" />
    //               </group>
    //               <group
    //                 name="Light002"
    //                 position={[407.625, 590.386, -100.545]}
    //                 rotation={[1.89, 0.881, -2.045]}
    //                 scale={100}>
    //                 <group name="Object_126" rotation={[Math.PI / 2, 0, 0]}>
    //                   <group name="Object_127" />
    //                 </group>
    //               </group>
    //               <group
    //                 name="Camera002"
    //                 position={[735.889, 495.831, 692.579]}
    //                 rotation={[-Math.PI, 0.756, 2.68]}
    //                 scale={100}>
    //                 <group name="Object_129" />
    //               </group>
    //               <group
    //                 name="Light003"
    //                 position={[407.625, 590.386, -100.545]}
    //                 rotation={[1.89, 0.881, -2.045]}
    //                 scale={100}>
    //                 <group name="Object_131" rotation={[Math.PI / 2, 0, 0]}>
    //                   <group name="Object_132" />
    //                 </group>
    //               </group>
    //               <group
    //                 name="Camera003"
    //                 position={[735.889, 495.831, 692.579]}
    //                 rotation={[-Math.PI, 0.756, 2.68]}
    //                 scale={100}>
    //                 <group name="Object_134" />
    //               </group>
    //               <group name="Ch44001" position={[0, 141.635, 15.009]} />
    //               <group
    //                 name="Plane006"
    //                 position={[-0.726, 161.462, 4.869]}
    //                 rotation={[-1.62, 0.004, -0.087]}
    //                 scale={16.019}>
    //                 <group name="Plane" />
    //                 <group name="Plane001" />
    //                 <group name="Plane002" />
    //                 <group name="Plane003" />
    //                 <group name="Plane004" />
    //                 <group name="Plane005" rotation={[-0.068, 0, 0]} />
    //                 <group name="Plane007" />
    //                 <group name="Plane008" />
    //                 <group name="Plane009" />
    //                 <group name="Plane010" rotation={[0.009, -0.122, -0.083]} scale={1.152} />
    //                 <group name="Plane011" />
    //                 <group name="Plane012" />
    //                 <group name="Plane013" />
    //                 <group name="Plane015" />
    //                 <group name="Plane014" scale={1.032} />
    //                 <group name="Plane016" scale={0.971} />
    //                 <group name="Plane017" scale={0.949} />
    //                 <group name="NurbsPath" />
    //                 <group name="NurbsPath001" />
    //                 <group name="cable" />
    //                 <group name="NurbsPath002" />
    //                 <group name="NurbsPath003" />
    //                 <group
    //                   name="Plane018"
    //                   position={[0.013, -0.007, 1.361]}
    //                   rotation={[0.303, -0.216, 0.062]}
    //                   scale={0.09}
    //                 />
    //               </group>
    //             </group>
    //           </group>
    //         </group>
    //       </group>
    //     </group>
    //   </group>
    // </group>
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.017}>
          <group name="e779cecba394439eb4f3b40699d8d016fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh
                    name="Object_6"
                    geometry={nodes.Object_6.geometry}
                    material={materials.Ch44_Body}
                    skeleton={nodes.Object_6.skeleton}
                  />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.Ch44_body1}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <group name="Ch44" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Robo;
